### ISSUE TITLE
PdfTranslator

### ISSUE THREAD

**Issue by aplocher** [Atalasoft/searchable-pdf-generator#4]
According to [this page](https://www.atalasoft.com/Products/OCR) Searchable PDFs should be using PdfTranslator.  I don't see any references to this in the code.

In addition, it seems to require a PdfDocument license.  Is this correct?  Shouldn't I be able to create a searchable Pdf with my DotImage license?

This is the exception I get after it iterates each page and Ocr's them:

```
Unhandled Exception: Atalasoft.Imaging.AtalasoftLicenseException: Pdf Generation libraries require a PdfDoc license file
   at Atalasoft.PdfDoc.Generating.PdfGeneratedDocument.a(Type A_0, Object A_1, PdfGeneratedDocument A_2)
   at Atalasoft.PdfDoc.Generating.PdfGeneratedDocument.SetLicense(Type t, Object o, PdfGeneratedDocument doc)
   at Atalasoft.PdfDoc.Generating.PdfGeneratedDocument..ctor(String userPassword, String ownerPassword, Stream stm, Boolean attemptToImportForeignContent, PdfDocumentLoadedProgress pageLoaded, RepairOptions repairOptions)
   at Atalasoft.PdfDoc.Generating.PdfGeneratedDocument..ctor(String userPassword, String ownerPassword, Stream stm, Boolean attemptToImportForeignContent, PdfDocumentLoadedProgress pageLoaded)
   at Atalasoft.PdfDoc.Generating.PdfGeneratedDocument..ctor(Stream stm)
   at SearchablePdfGenerator.Program.FormPdf(String srcPath, String outPath, IList`1 ocrPages, IFontMapper fontMapper, IFontBuilder fontBuilder) in C:\src\searchable-pdf-generator\SearchablePdfGenerator\Program.cs:line 97
   at SearchablePdfGenerator.Program.GenerateSearchablePdf(String srcPath, String outPath) in C:\src\searchable-pdf-generator\SearchablePdfGenerator\Program.cs:line 70
   at SearchablePdfGenerator.Program.Main(String[] args) in C:\src\searchable-pdf-generator\SearchablePdfGenerator\Program.cs:line 42
```

Which is located here:

```
private static void FormPdf(string srcPath, string outPath, IList<OcrPage> ocrPages, IFontMapper fontMapper,
    IFontBuilder fontBuilder)
{
    using (var inStm = File.OpenRead(srcPath))
    using (_pdfTextDocument = new PdfTextDocument(inStm))
    using (var genDoc = new PdfGeneratedDocument(inStm)) // <-- here
    {
        genDoc.Resources.Images.Compressors.Add(new AtalaImageCompressor());
        using (var images = new FileSystemImageSource(srcPath, true))
            AddTextLayers(genDoc, ocrPages, fontMapper, fontBuilder, images);

        genDoc.Save(outPath);
    }
}
```

**Comment by gdv1811** [comment]
Hello Adam Plocher,
As you noted in another issue, we have two demo application. This one creates searchable PDF without PdfTraslator, but uses PdfGeneratedDocument. PdfGeneratedDocument requires PdfDoc license. Therefore, if you do not have it, please use sample from Atalasoft website (http://atalasupport.net/demos/LegacyDemos-11.1/SearchablePDFDemo.zip).

Thanks,
Dmitry
